##
# SYNOPSIS
#       pg_wait_*
#
# DESCRIPTION
#       PostgreSQL backend client count group by wait event type since 9.6
#
# OPTIONS
#       Tags       [cluster]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    90600 ~ higher
#       Source     420-pg_wait.yml
#
# METRICS
#       datname (LABEL)
#           Name of the database this backend is connected to
#       event (LABEL)
#           Wait event type, LWLock, Lock, BufferPin, Activity, Extension, Client, IPC, Timeout, IO
#       count (GAUGE)
#           Count of WaitEvent on target database
#
pg_wait:
  name: pg_wait
  desc: PostgreSQL backend client count group by wait event type since 9.6

  query: |
    SELECT datname, wait_event_type AS event, count(*) AS count FROM pg_stat_activity WHERE datname NOT IN ('template0', 'template1') AND backend_type = 'client backend' AND pid <> pg_backend_pid() GROUP BY 1, 2;
  ttl: 10
  min_version: 090600
  tags:
    - cluster

  metrics:
    - datname:
        usage: LABEL
        description: Name of the database this backend is connected to
    - event:
        usage: LABEL
        description: Wait event type, LWLock, Lock, BufferPin, Activity, Extension, Client, IPC, Timeout, IO
    - count:
        usage: GAUGE
        description: Count of WaitEvent on target database


