##
# SYNOPSIS
#       pgbouncer_pool.pgbouncer_pool_108_115_*
#
# DESCRIPTION
#       Pgbouncer pool stats (1.08-1.15)
#
# OPTIONS
#       Tags       [pgbouncer]
#       TTL        10
#       Priority   0
#       Timeout    100ms
#       Fatal      false
#       Version    10800 ~ 11600
#       Source     940-pgbouncer_pool.yml
#
# METRICS
#       database (LABEL)
#           Database name of this pool
#       user (LABEL)
#           User name of this pool
#       cl_active (GAUGE)
#           Client connections that are linked to server connection and can process queries
#       cl_waiting (GAUGE)
#           Client connections that have sent queries but have not yet got a server connection
#       sv_active (GAUGE)
#           Server connections that are linked to a client
#       sv_idle (GAUGE)
#           Server connections that are unused and immediately usable for client queries
#       sv_used (GAUGE)
#           Server connections that have been idle for more than server_check_delay (means have to run check query)
#       sv_tested (GAUGE)
#           Server connections that are currently running reset or check query
#       sv_login (GAUGE)
#           Server connections currently in the process of logging in
#       maxwait (GAUGE)
#           How long the first(oldest) client in the queue has waited, in seconds, key metric
#       maxwait_us (GAUGE)
#           Microsecond part of the maximum waiting time.
#       pool_mode (LABEL)
#           Pooling mode in use
#
pgbouncer_pool_124:
  name: pgbouncer_pool
  desc: Pgbouncer pool stats (1.24+)    # http://www.pgbouncer.org/usage.html#show-pools
  query: SHOW POOLS;
  ttl: 10
  min_version: 12400
  tags:
    - pgbouncer

  metrics:
    - database:
        usage: LABEL
        rename: datname
        description: Database name of this pool
    - user:
        usage: LABEL
        description: User name of this pool
    - cl_active:
        usage: GAUGE
        rename: active_clients
        description: Client connections that are linked to server connection and can process queries
    - cl_waiting:
        usage: GAUGE
        rename: waiting_clients
        description: Client connections that have sent queries but have not yet got a server connection
    - cl_active_cancel_req:
        usage: GAUGE
        rename: active_cancel_clients
        description: Client connections that have forwarded query cancellations to the server and are waiting for the server response.
    - cl_waiting_cancel_req:
        usage: GAUGE
        rename: cancel_clients
        description: Client connections that have not forwarded query cancellations to the server yet.
    - sv_active:
        usage: GAUGE
        rename: active_servers
        description: Server connections that are linked to a client
    - sv_active_cancel:
        usage: GAUGE
        rename: active_cancel_servers
        description: Server connections that are currently forwarding a cancel request
    - sv_being_canceled:
        usage: GAUGE
        rename: cancel_servers
        description: cancel requests have completed that were sent to cancel a query on this server
    - sv_idle:
        usage: GAUGE
        rename: idle_servers
        description: Server connections that are unused and immediately usable for client queries
    - sv_used:
        usage: GAUGE
        rename: used_servers
        description: Server connections that have been idle for more than server_check_delay (means have to run check query)
    - sv_tested:
        usage: GAUGE
        rename: tested_servers
        description: Server connections that are currently running reset or check query
    - sv_login:
        usage: GAUGE
        rename: login_servers
        description: Server connections currently in the process of logging in
    - maxwait:
        usage: GAUGE
        description: How long the first(oldest) client in the queue has waited, in seconds, key metric
    - maxwait_us:
        usage: GAUGE
        description: Microsecond part of the maximum waiting time.
    - pool_mode:
        usage: LABEL
        description: Pooling mode in use
    - load_balance_hosts:
        usage: LABEL
        description: The load_balance_hosts in use

pgbouncer_pool_118_123:
  name: pgbouncer_pool
  desc: Pgbouncer pool stats (1.18-1.23)    # http://www.pgbouncer.org/usage.html#show-pools
  query: SHOW POOLS;
  ttl: 10
  min_version: 11800
  max_version: 12400
  tags:
    - pgbouncer

  metrics:
    - database:
        usage: LABEL
        rename: datname
        description: Database name of this pool
    - user:
        usage: LABEL
        description: User name of this pool
    - cl_active:
        usage: GAUGE
        rename: active_clients
        description: Client connections that are linked to server connection and can process queries
    - cl_waiting:
        usage: GAUGE
        rename: waiting_clients
        description: Client connections that have sent queries but have not yet got a server connection
    - cl_active_cancel_req:
        usage: GAUGE
        rename: active_cancel_clients
        description: Client connections that have forwarded query cancellations to the server and are waiting for the server response.
    - cl_waiting_cancel_req:
        usage: GAUGE
        rename: cancel_clients
        description: Client connections that have not forwarded query cancellations to the server yet.
    - sv_active:
        usage: GAUGE
        rename: active_servers
        description: Server connections that are linked to a client
    - sv_active_cancel:
        usage: GAUGE
        rename: active_cancel_servers
        description: Server connections that are currently forwarding a cancel request
    - sv_being_canceled:
        usage: GAUGE
        rename: cancel_servers
        description: cancel requests have completed that were sent to cancel a query on this server
    - sv_idle:
        usage: GAUGE
        rename: idle_servers
        description: Server connections that are unused and immediately usable for client queries
    - sv_used:
        usage: GAUGE
        rename: used_servers
        description: Server connections that have been idle for more than server_check_delay (means have to run check query)
    - sv_tested:
        usage: GAUGE
        rename: tested_servers
        description: Server connections that are currently running reset or check query
    - sv_login:
        usage: GAUGE
        rename: login_servers
        description: Server connections currently in the process of logging in
    - maxwait:
        usage: GAUGE
        description: How long the first(oldest) client in the queue has waited, in seconds, key metric
    - maxwait_us:
        usage: GAUGE
        description: Microsecond part of the maximum waiting time.
    - pool_mode:
        usage: LABEL
        description: Pooling mode in use



pgbouncer_pool_116_118:
  name: pgbouncer_pool
  desc: Pgbouncer pool stats (1.16-1.17)    # http://www.pgbouncer.org/usage.html#show-pools
  query: SHOW POOLS;
  ttl: 10
  min_version: 11600
  max_version: 11800
  tags:
    - pgbouncer

  metrics:
    - database:
        usage: LABEL
        rename: datname
        description: Database name of this pool
    - user:
        usage: LABEL
        description: User name of this pool
    - cl_active:
        usage: GAUGE
        rename: active_clients
        description: Client connections that are linked to server connection and can process queries
    - cl_waiting:
        usage: GAUGE
        rename: waiting_clients
        description: Client connections that have sent queries but have not yet got a server connection
    - cl_cancel_req:
        usage: GAUGE
        rename: cancel_clients
        description: Client connections that have not forwarded query cancellations to the server yet.
    - sv_active:
        usage: GAUGE
        rename: active_servers
        description: Server connections that are linked to a client
    - sv_idle:
        usage: GAUGE
        rename: idle_servers
        description: Server connections that are unused and immediately usable for client queries
    - sv_used:
        usage: GAUGE
        rename: used_servers
        description: Server connections that have been idle for more than server_check_delay (means have to run check query)
    - sv_tested:
        usage: GAUGE
        rename: tested_servers
        description: Server connections that are currently running reset or check query
    - sv_login:
        usage: GAUGE
        rename: login_servers
        description: Server connections currently in the process of logging in
    - maxwait:
        usage: GAUGE
        description: How long the first(oldest) client in the queue has waited, in seconds, key metric
    - maxwait_us:
        usage: GAUGE
        description: Microsecond part of the maximum waiting time.
    - pool_mode:
        usage: LABEL
        description: Pooling mode in use




pgbouncer_pool_108_115:
  name: pgbouncer_pool
  desc: Pgbouncer pool stats (1.08-1.15)   # http://www.pgbouncer.org/usage.html#show-pools
  query: SHOW POOLS;
  ttl: 10
  min_version: 10800
  max_version: 11600
  tags:
    - pgbouncer

  metrics:
    - database:
        usage: LABEL
        rename: datname
        description: Database name of this pool
    - user:
        usage: LABEL
        description: User name of this pool
    - cl_active:
        usage: GAUGE
        rename: active_clients
        description: Client connections that are linked to server connection and can process queries
    - cl_waiting:
        usage: GAUGE
        rename: waiting_clients
        description: Client connections that have sent queries but have not yet got a server connection
    - sv_active:
        usage: GAUGE
        rename: active_servers
        description: Server connections that are linked to a client
    - sv_idle:
        usage: GAUGE
        rename: idle_servers
        description: Server connections that are unused and immediately usable for client queries
    - sv_used:
        usage: GAUGE
        rename: used_servers
        description: Server connections that have been idle for more than server_check_delay (means have to run check query)
    - sv_tested:
        usage: GAUGE
        rename: tested_servers
        description: Server connections that are currently running reset or check query
    - sv_login:
        usage: GAUGE
        rename: login_servers
        description: Server connections currently in the process of logging in
    - maxwait:
        usage: GAUGE
        description: How long the first(oldest) client in the queue has waited, in seconds, key metric
    - maxwait_us:
        usage: GAUGE
        description: Microsecond part of the maximum waiting time.
    - pool_mode:
        usage: LABEL
        description: Pooling mode in use

